* What is it you want to do with your life?
Last week I had an out-of-the-blue meeting with [[http://www.cs.bath.ac.uk/~jjb/][Joanna Bryson]] to discuss the overlaps in our research. We both did stuff with emotional models for agents, but it was pretty tangential for both of us.

The conversation turned to how I might go about commercialising my research. I'd had a conversation with some guys at a business incubator that suggested I hold back publication of my ideas in order to hold on to intellectual property that could attract investors. She advocated the opposite: publishing as much of my research as possible in order to build up a reputation for myself. Additionally, she said I should focus my effort on turning my research into a game. Then she posed me a question: "/Well, what is it you want to do with your life?/".

I paused for a few seconds and responded: "/I want to create something new and original/". It's funny how strange it was to be asked that question. I don't think anyone has asked me that before! It jarred me for a moment, and I felt a little ashamed that I couldn't reply immediately with a response. I mean, don't all successful and ambitious people have this question at the back of their mind every day when they wake up? But when I relaxed and contemplated my answer, it seemed obvious.

I'm about to reach a point in my life where I have a huge decision to make. What do I want to do after I've graduated from the EngD? The way I see it, my options are:

1. To get funding to make a game full-time based on my research
2. To go and do a post-doc in Japan
3. To commercialise my research with a startup incubator
4. To get a development job here in Bristol, and save money for 1. or 3.

There's no reason I can't do number 1. in my free time while pursuing one of the other options. And in fact, I am, by working on small games now and putting them on my website. But to make a decent game will take my full-time commitment, and for that I need enough money to at least cover my living costs. That means either saving up enough, or getting funding.

I'm glad Joanna asked me that question. Until last week, I'd been unsure what to do next. But being asked what I wanted to do with my life forced me to make my choice. Though my next step might be unclear, I know where I want it to take me eventually.
